In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
df=pd.read_csv("train_set.csv")

In [5]:
df.head()

Date     Day  CodedDay  Zone  Weather  Temperature  Traffic
0  1-01-2017  Sunday         7     1       21           17        1
1  1-01-2017  Sunday         7     2       12           34        2
2  1-01-2017  Sunday         7     3       25           24        2
3  1-01-2017  Sunday         7     4       46           41        4
4  1-01-2017  Sunday         7     5       33           19        3

In [6]:
df.tail()

Date       Day  CodedDay  Zone  Weather  Temperature  Traffic
52411  31-12-2017  Saturday         6   140       15           35        2
52412  31-12-2017  Saturday         6   141       27           11        4
52413  31-12-2017  Saturday         6   142       25           12        3
52414  31-12-2017  Saturday         6   143       24           28        1
52415  31-12-2017  Saturday         6   144       14           24        1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52416 entries, 0 to 52415
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Date         52416 non-null  object
 1   Day          52416 non-null  object
 2   CodedDay     52416 non-null  int64 
 3   Zone         52416 non-null  int64 
 4   Weather      52416 non-null  int64 
 5   Temperature  52416 non-null  int64 
 6   Traffic      52416 non-null  int64 
dtypes: int64(5), object(2)
memory usage: 2.8+ MB


In [8]:
from sklearn.preprocessing import LabelEncoder


In [9]:
le=LabelEncoder()

In [10]:
df['Date']=le.fit_transform(df['Date'])
df.head()

Date     Day  CodedDay  Zone  Weather  Temperature  Traffic
0     0  Sunday         7     1       21           17        1
1     0  Sunday         7     2       12           34        2
2     0  Sunday         7     3       25           24        2
3     0  Sunday         7     4       46           41        4
4     0  Sunday         7     5       33           19        3

In [11]:
df['Date'].unique()

array([  0, 132, 263, 292, 304, 316, 328, 340, 352,  12,  24,  36,  48,
        60,  72,  84,  96, 108, 120, 144, 156, 168, 180, 192, 204, 216,
       228, 240, 252, 275,   1, 133, 264, 293, 305, 317, 329, 341, 353,
        13,  25,  37,  49,  61,  73,  85,  97, 109, 121, 145, 157, 169,
       181, 193, 205, 217, 229, 241,   2, 134, 265, 294, 306, 318, 330,
       342, 354,  14,  26,  38,  50,  62,  74,  86,  98, 110, 122, 146,
       158, 170, 182, 194, 206, 218, 230, 242, 253, 276, 286,   3, 135,
       266, 295, 307, 319, 331, 343, 355,  15,  27,  39,  51,  63,  75,
        87,  99, 111, 123, 147, 159, 171, 183, 195, 207, 219, 231, 243,
       254, 277,   4, 136, 267, 296, 308, 320, 332, 344, 356,  16,  28,
        40,  52,  64,  76,  88, 100, 112, 124, 148, 160, 172, 184, 196,
       208, 220, 232, 244, 255, 278, 287,   5, 137, 268, 297, 309, 321,
       333, 345, 357,  17,  29,  41,  53,  65,  77,  89, 101, 113, 125,
       149, 161, 173, 185, 197, 209, 221, 233, 245, 256, 279,   

In [12]:
df.tail()

Date       Day  CodedDay  Zone  Weather  Temperature  Traffic
52411   291  Saturday         6   140       15           35        2
52412   291  Saturday         6   141       27           11        4
52413   291  Saturday         6   142       25           12        3
52414   291  Saturday         6   143       24           28        1
52415   291  Saturday         6   144       14           24        1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52416 entries, 0 to 52415
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Date         52416 non-null  int32 
 1   Day          52416 non-null  object
 2   CodedDay     52416 non-null  int64 
 3   Zone         52416 non-null  int64 
 4   Weather      52416 non-null  int64 
 5   Temperature  52416 non-null  int64 
 6   Traffic      52416 non-null  int64 
dtypes: int32(1), int64(5), object(1)
memory usage: 2.6+ MB


In [14]:
x=df.iloc[:,2:6].values

In [15]:
y=df.iloc[:,6:7].values

In [16]:
x

array([[  7,   1,  21,  17],
       [  7,   2,  12,  34],
       [  7,   3,  25,  24],
       ...,
       [  6, 142,  25,  12],
       [  6, 143,  24,  28],
       [  6, 144,  14,  24]], dtype=int64)

In [17]:
x.shape

(52416, 4)

In [18]:
y

array([[1],
       [2],
       [2],
       ...,
       [3],
       [1],
       [1]], dtype=int64)

In [19]:
y.shape

(52416, 1)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)

In [22]:
X_train.shape

(36691, 4)

In [23]:
y_train.shape

(36691, 1)

In [24]:
X_test.shape

(15725, 4)

In [25]:
y_test.shape

(15725, 1)

In [26]:
#feature scaling


In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
sc=StandardScaler()

In [29]:
X_train=sc.fit_transform(X_train)

In [30]:
X_test=sc.fit_transform(X_test)

In [31]:
X_train

array([[-1.00646664, -1.47919159, -0.24484033, -0.9125374 ],
       [-1.50642964, -0.32176381,  1.27681809, -0.9125374 ],
       [ 0.49342238, -1.50330467,  1.27681809, -0.9125374 ],
       ...,
       [ 1.49334839, -1.16572157,  1.34927801,  1.67768533],
       [ 1.49334839, -0.87636462,  1.63911771,  0.03721093],
       [ 1.49334839,  0.78743782,  0.11745929,  1.15964078]])

In [32]:
X_train

array([[-1.00646664, -1.47919159, -0.24484033, -0.9125374 ],
       [-1.50642964, -0.32176381,  1.27681809, -0.9125374 ],
       [ 0.49342238, -1.50330467,  1.27681809, -0.9125374 ],
       ...,
       [ 1.49334839, -1.16572157,  1.34927801,  1.67768533],
       [ 1.49334839, -0.87636462,  1.63911771,  0.03721093],
       [ 1.49334839,  0.78743782,  0.11745929,  1.15964078]])

In [33]:
from sklearn.ensemble import RandomForestRegressor

In [34]:
regressor=RandomForestRegressor(n_estimators=300,random_state=0)

In [35]:
regressor.fit(X_train,y_train)

C:\Users\user\AppData\Local\Temp\ipykernel_24184\3585153985.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train,y_train)


RandomForestRegressor(n_estimators=300, random_state=0)

In [36]:
y_pred=regressor.predict(X_test)

In [43]:
X_test

array([[ 0.51543711, -1.52816801,  0.88692805,  1.08510432],
       [ 0.0152675 ,  0.4578921 , -0.48566041, -0.73148026],
       [-1.48524133, -1.59995332,  1.53710154, -0.81798429],
       ...,
       [-0.48490211, -1.43245427,  0.30899607,  1.60412849],
       [ 0.51543711,  0.79289019, -1.71376588,  0.13356002],
       [ 0.0152675 ,  1.67824229,  0.81468655,  0.47957613]])

In [37]:
y_pred

array([2.5475    , 2.06583333, 2.61333333, ..., 2.36333333, 3.24333333,
       2.99666667])

In [38]:
if(y_pred.all()<2.5):
    y_pred=np.round(y_pred-0.5)
else:
    y_pred=np.round(y_pred+0.5)

In [39]:
y_pred

array([2., 2., 2., ..., 2., 3., 2.])

In [40]:
df_new=(y_pred-y_test)/y_test
df_new=round(df_new.mean()*100,2)

In [41]:
df_new #Error

14.51

In [42]:
a=100-df_new
print("Accuracy:",a,"%")

Accuracy: 85.49 %


In [61]:
a=[[1,4,14,38]]
test=sc.fit_transform(a)
y_new_test=regressor.predict(test)

In [62]:
print(y_new_test)
if(y_new_test <2.5):
    y_new_test=np.round(y_new_test-0.5)
else:
    y_new_test=np.round(y_new_test+0.5)
print(y_new_test)

[3.25166667]
[4.]


In [43]:
#SVM

In [63]:
from sklearn.svm import SVR 
regressor_svm=SVR(kernel='rbf')

In [64]:
regressor_svm.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [46]:
y_pred_svm=regressor_svm.predict(X_test)


In [47]:
y_pred_svm

array([2.92724728, 2.99823707, 3.05895424, ..., 2.98293563, 2.97403231,
       3.12536316])

In [48]:
if(y_pred_svm.all()<2.5):
    y_pred_svm=np.round(y_pred_svm-0.5)
else:
    y_pre_svm=np.round(y_pred_svm+0.5)

In [49]:
df_new=(y_pred_svm-y_test)/y_test
df_new=round(df_new.mean()*100,2)

In [50]:
df_new #Error

10.03

In [51]:
a=100-df_new
print("Accuracy:",a,"%")

Accuracy: 89.97 %


In [65]:
a=[[1,4,14,38]]
test=sc.fit_transform(a)
y_new_test=regressor_svm.predict(test)

In [66]:
print(y_new_test)
if(y_new_test <2.5):
    y_new_test=np.round(y_new_test-0.5)
else:
    y_new_test=np.round(y_new_test+0.5)
print(y_new_test)

[3.09865658]
[4.]
